#!/usr/bin/env python3

import reversi as rv

game = rv.Reversi()
game.printBoard()
game.printPlayer()

#game loop
while (not game.finished):
    
    move = game.getMove()
    while not game.playMove(move):
            move = game.getMove()
            
    game.printBoard()

    game.changePlayer()
    game.printPlayer()
