#!/usr/bin/env python3

"""
options:
    --vis
        force printing board to command line
    
    --no-vis
        only output board to board.txt

    --ai=n
        player 2 will be an ai, level n
"""

import reversi as rv
import ai
import sys


game = rv.Reversi()



visible = True
fname = None
ai_enabled = False

if len(sys.argv) > 1:
    if "--vis" in sys.argv:
        visible = True
    elif "--no-vis" in sys.argv:
        visible = False
        fname = "board.txt"
    for i in range(1, ai.levels + 1):
        if "--ai=" + str(i) in sys.argv:
            print("AI enabled!")
            ai_enabled = True
            level = i
            rev_ai = ai.ReversiAI(game, level)

game.findValidMoves()
game.printBoard(playable=True, filename=fname)
game.printPlayer()


#game loop
while (not game.finished):
   

    if ai_enabled == True and game.curr_player == "White":
        print("getting move from AI...")
        move = rev_ai.getMove(level)
        print("AI played: ", move)
    else:
        move = game.getMove(fname)

    while not game.playMove(move, vis=visible):
        if ai_enabled == True and game.curr_player == "White":
            print("getting move from AI...")
            move = rev_ai.getMove(level)
            print("AI played: ", move)
        else:
            move = game.getMove(fname)
            

    game.findValidMoves("all")
    game.changePlayer()

    game.printBoard(playable=True, filename=fname)
   

    if visible and not game.finished:
        game.printScore()
        game.printPlayer()

print("Game finished!")
game.printScore()
